# Generated by Django 2.2.2 on 2019-09-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
    ]
