# Generated by Django 2.2.2 on 2019-09-22 15:52

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20190922_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to=core.models.upload_to)),
                ('authors', models.ManyToManyField(related_name='books', to='core.Author')),
                ('categories', models.ManyToManyField(related_name='books', to='core.Category')),
                ('read_by', models.ManyToManyField(related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
                'default_related_name': 'books',
            },
        ),
    ]
