openapi: 3.0.0
info:
  version: 0.0.0
  title: API for NomadBooks
servers:
  - url: http://localhost:{port}/api/v1
    description: Local
    variables:
      port:
        default: '5000'
paths:
  /auth/login/:
    $ref: 'paths/login.yml'
  /auth/logout/:
    $ref: 'paths/logout.yml'
  /auth/registration/:
    $ref: 'paths/registration.yml'
  /auth/registration/verify-email/:
    $ref: 'paths/verification.yml'
  /categories/:
    $ref: 'paths/categories.yml'
schemas:
  Message:
    $ref: 'schemas/Message.yml'
  Token:
    $ref: 'schemas/Token.yml'